### ISSUE TITLE
JSQMessagesViewController

### ISSUE THREAD

**Issue by 0xPr0xy** [relatedcode/ChatUIAlternatives#1]
Nice idea to create this repository.

JSQMessagesViewController is now without maintainer, which is bad news.
However, if a maintainer would step up, or preferably multiple maintainers, it does not have to be deprecated IMO.
We could maintain it, and port it to swift as a community effort.
Therefore I think there is a case to be made to also list JSQMessagesViewController, but to make clear that we have to find people willing to maintain this project, and a way to list people that are stepping up as possible maintainers, in order for it to become a viable solution.

What are your thoughts on this?

**Comment by 0xPr0xy** [comment]
If we consider this approach. I would add the SwiftExample in the JSQMessagesViewController repository to a new repository (non-personal, shared by all people willing to maintain) for example: https://github.com/0xPr0xy/PYMessagesViewController
And point it to a forked JSQMessagesViewController in the same repository

**Comment by SD10** [comment]
@0xPr0xy Ultimately, I think porting JSQMessagesViewController to Swift allows for a greater number of potential contributors as well as brings some fresh blood to the project.

I'm not a fan of naming prefixes, I think a name like MessageKit and hosting it in an organization is more suited to building a community around the project.

**Comment by 0xPr0xy** [comment]
@SD10 fully agree
